# Generated by Django 3.1.4 on 2020-12-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sproduct', '0001_initial'),
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sproduct.sproduct', verbose_name='상품')),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suser.suser', verbose_name='유저')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'db_order',
            },
        ),
    ]
