# Generated by Django 3.1.4 on 2020-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorder', '0002_auto_20201207_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorder',
            name='status',
            field=models.CharField(choices=[('대기중', '대기중'), ('결제대기', '결제대기'), ('결제완료', '결제완료'), ('환불', '환불')], default='대기중', max_length=32, verbose_name='상태'),
        ),
    ]
