# Generated by Django 3.1.4 on 2020-12-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suser',
            name='level',
            field=models.CharField(choices=[('admin', '관리자'), ('user', '유저')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
