"""
Django settings for djangprac2 project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'dd+np#+^f8yu489_#xe*y_t708jfqo9#i(#wwi5*4(bev0i!_='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

BATON = {
    'SITE_HEADER': '쇼핑몰 백오피스',
    'SITE_TITLE': '쇼핑몰 백오피스',
    'INDEX_TITLE': '쇼핑몰 관리자페이지',
    'SUPPORT_HREF': 'mailto:test@test.com',
    'COPYRIGHT': 'copyright © 2020 KHS',
    'POWERD_BY': '<a href="#">쇼핑몰</a>',
    'MENU_TITLE': '쇼핑몰 페이지',
    'MENU': (
        {'type': 'title', 'label': 'main', 'apps': (
            'suser', 'sorder', 'sproduct')},
        {
            'type': 'app',
            'name': 'suser',
            'label': '사용자',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'name': 'suser',
                    'label': '사용자'
                },
            )
        },
        {
            'type': 'free', 'label': '주문', 'default_open': True, 'children': [
                {'type': 'model', 'label': '주문', 'name': 'sorder', 'app': 'sorder'},
                {'type': 'free', 'label': '주문',
                    'url': '/admin/sorder/sorder/'},
                {'type': 'free', 'label': '주문 날짜 뷰',
                    'url': '/admin/sorder/sorder/date_view/'}

            ]
        },
        {
            'type': 'app',
            'name': 'sproduct',
            'label': '상품',
            'models': (
                {
                    'name': 'sproduct',
                    'label': '상품'
                },
            )
        },
        {'type': 'free', 'label': '매뉴얼', 'url': '/admin/manual'},
    ),
}

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'suser.apps.SuserConfig',  # 이렇게 apps안에 suserconfig로 접근해서 표기될 이름을 가져옴
    'sproduct.apps.SproductConfig',
    'sorder.apps.SorderConfig',
    'baton.autodiscover'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangprac2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # 프로젝트 안에 템플릿을 찾도록 경로지정 # os.path.join은 경로를 연결
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,  # 각 앱들 안에있는 템플릿 폴더를 찾아보는거
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangprac2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
